spring:
  application:
    name: springdocs
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  datasource:
    url: jdbc:postgresql://34.93.13.169:5432/springdocs
    username: postgres
    password: Postgres@123
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only